#################################
## General parameters
#################################

# Benchmark file name
benchmark: 
  - ./ising/benchmarks/G/G1.txt
  - ./ising/benchmarks/G/G6.txt
  - ./ising/benchmarks/G/G14.txt
  - ./ising/benchmarks/TSP/burma14.tsp
  - ./ising/benchmarks/TSP/ulysses16.tsp
  - ./ising/benchmarks/TSP/ulysses22.tsp
  - ./ising/benchmarks/Knapsack/jeu_100_25_1.txt
  - ./ising/benchmarks/Knapsack/jeu_200_25_1.txt
  - ./ising/benchmarks/Knapsack/jeu_100_50_1.txt

# Solver to use: [BRIM, SA, DSA, inSituSA, bSB, dSB, SCA, Multiplicative, CIM, all]
solvers:
  - bSB
  - dSB

# Number of trials
nb_runs: 100

# Use gurobi or not
use_gurobi: False

# Use multiprocessing or not
use_multiprocessing: False

nb_cores: 16

# Initialization seed or use eigenvector of matrix
initialization_seed: 42
eigenvalue_start: False

# Logging or not
gen_logfile: False
logfile_discrimination: None
#################################
## Solvers hyperparameters
#################################

# Parameters for SB
num_iterations_SB: 10000
dtSB: 
  - 0.25
  - 0.5
  - 0.75
  - 1.0
  - 1.25
a0: 1.0
c0: 0.0
seed: 100

#################################
## Problems hyperparameters
#################################

# Parameters for TSP
weight_constant: 1.2

# Parameters for MIMO
SNR: 10
nb_trials: 1
mimo_seed: 12
is_hamming_encoding: False

#################################
## Specific Stages hyperparameters
#################################

# Parameters for quantization stage
quantization: False
quantization_precision: 1.5
scale_to_integer: False

# Parameters for npmos stage
offset_type: others
offset_ratio: 0.3

# Parameters for noise stage
device_noise: False
noise_level: 0.1

mismatch_std: 0.0
combine_nodes: False
#################################
## Dummy creator hyperparameters
#################################
dummy_creator: False

# Parameters for dummy MIMO
dummy_seed: 42
dummy_qam: 4
dummy_snr: 8
dummy_spacing: 1.0
dummy_user_num: 16
dummy_ant_num: 64
dummy_case_num: 10

# Parameters for dummy MaxCut
dummy_quadratic: False
dummy_local_optima: False

# Parameters for dummy MaxCut/TSP/ATSP/Knapsack
dummy_size: 20

# for TSP/ATSP
dummy_weight_constant: 0.0

# for dummy Knapsack
dummy_density: 1
dummy_penalty_value: 1.0
dummy_bit_width: 16
