#################################
## General parameters
#################################

# Benchmark file name
benchmark: ./ising/benchmarks/MIMO/user5_ant5_M16.txt

# Solver to use: [BRIM, SA, DSA, inSituSA, bSB, dSB, SCA, Multiplicative, CIM, all]
solvers:
  - bSB

# Number of trials
nb_runs: 5

# Use gurobi or not
use_gurobi: False

# Use multiprocessing or not
use_multiprocessing: False

nb_cores: 16

# Initialization seed or use eigenvector of matrix
initialization_seed: 42
eigenvalue_start: False

# Logging or not
gen_logfile: False
logfile_discrimination: None

#################################
## Solvers hyperparameters
#################################

# Parameters for SA
num_iterations_SA: 1
T: 50.0
T_final: 0.05
seed: 100

# Parameters for SCA
num_iterations_SCA: 1
T_init_SCA: 50.0
T_final_SCA: 0.5
q: 0.0
q_final: 10.0

# Parameters for in-Situ SA
initial_temp_inSituSA: 690
T_final_inSituSA: 0.5
num_iterations_inSituSA: 1
nb_flips: 1

# Parameters for BRIM
num_iterations_BRIM: 1
dtBRIM: 1e-6  # 10us
stop_criterion: 1e-6  # 1uV
capacitance: 1
resistance: 1
do_flipping: True
coupling_annealing: True
probability_start: 0.001799

# Parameters for SB
num_iterations_SB: 1
dtbSB: 0.01
dtdSB: 0.01
a0: 1.0
c0: 0.0

#################################
## Problems hyperparameters
#################################

# Parameters for TSP
weight_constant: 0

# Parameters for MIMO
SNR: 10
nb_trials: 100
mimo_seed: 12
is_hamming_encoding: False

#################################
## Specific Stages hyperparameters
#################################

# Parameters for quantization stage
quantization: False
quantization_precision: 1.5
scale_to_integer: False

# Parameters for npmos stage
offset_type: others
offset_ratio: 0.3

# Parameters for noise stage
device_noise: False
noise_level: 0.1

# Parameters for mismatch stage
mismatch_std: 0.0

# Parameters for combine nodes stage
combine_nodes: False
nodes_scaling: 2

#################################
## Dummy creator hyperparameters
#################################
dummy_creator: True

# Parameters for dummy MIMO
dummy_seed: 42
dummy_qam: 4
dummy_snr: 8
dummy_spacing: 1.0
dummy_user_num: 16
dummy_ant_num: 64
dummy_case_num: 10

# Parameters for dummy MaxCut
dummy_quadratic: False
dummy_local_optima: False

# Parameters for dummy MaxCut/TSP/ATSP/Knapsack
dummy_size: 20

# for TSP/ATSP
dummy_weight_constant: 0.0

# for dummy Knapsack
dummy_density: 1
dummy_penalty_value: 1.0
dummy_bit_width: 16
